export const SET_USERNAME = 'auth/SET_USERNAME';
export const SET_PASSWORD = 'auth/SET_PASSWORD';
export const SUBMIT_LOGIN_REQUEST = 'auth/SUBMIT_LOGIN_REQUEST';
export const SUBMIT_LOGIN_SUCCESS = 'auth/SUBMIT_LOGIN_SUCCESS';
export const SUBMIT_LOGIN_FAILURE = 'auth/SUBMIT_LOGIN_FAILURE';
