export const SET_USERNAME = 'auth/SET_USERNAME';
export const SET_PASSWORD = 'auth/SET_PASSWORD';
export const SUBMIT_LOGIN_REQUEST = 'auth/SUBMIT_LOGIN_REQUEST';
export const SUBMIT_LOGIN_SUCCESS = 'auth/SUBMIT_LOGIN_SUCCESS';
export const SUBMIT_LOGIN_FAILURE = 'auth/SUBMIT_LOGIN_FAILURE';
export const FETCH_PERSONAL_INFO_REQUEST = 'auth/FETCH_PERSONAL_INFO_REQUEST';
export const FETCH_PERSONAL_INFO_SUCCESS = 'auth/FETCH_PERSONAL_INFO_SUCCESS';
export const FETCH_PERSONAL_INFO_FAILURE = 'auth/FETCH_PERSONAL_INFO_FAILURE';
