export const ADD_FILE_FOR_UPLOAD = 'upload/ADD_FILE_FOR_UPLOAD';
export const DISCARD_FILE = 'upload/DISCARD_FILE';
export const UPLOAD_FILE_REQUEST = 'upload/UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS = 'upload/UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'upload/UPLOAD_FILE_FAILURE';
export const EDIT_TORRENT_TITLE = 'upload/EDIT_TORRENT_TITLE';
export const EDIT_TORRENT_TAGS = 'upload/EDIT_TORRENT_TAGS';