export const FETCH_POSTS_REQUEST = 'posts/FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'posts/FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'posts/FETCH_POSTS_FAILURE';
export const SELECT_POST = 'posts/SELECT_POST';
export const FETCH_DETAIL_REQUEST = 'posts/FETCH_DETAIL_REQUEST';
export const FETCH_DETAIL_SUCCESS = 'posts/FETCH_DETAIL_SUCCESS';
export const FETCH_DETAIL_FAILURE = 'posts/FETCH_DETAIL_FAILURE';
